name: black-linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install specific version of black
      run: pip install black==23.7.0

    - name: Run black linter
      run: black --check --verbose --diff ./ --include "\.ipynb$"
