name: black-linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install black
      run: pip install black

    - name: Run black and output files needing reformatting
      run: |
        black --check --diff ./ || echo "Some files need reformatting."
